name: flutter_profacto_sdk
description: A unofficial SDK for the profacto API.
version: 0.0.1
homepage: https://github.com/KevinRohn/flutter_profacto_sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.13.3
  package_info_plus: ^1.0.6
  device_info_plus: ^2.1.0
  path_provider: ^2.0.3
  cookie_jar: ^3.0.1
  flutter_web_auth: ^0.3.1
  enum_to_string: ^2.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

